# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HrCBXMZkaLkmEQZqkBRiLWL9mm_MbObm
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import lagrange

# Datos de la tabla
x = np.array([1, 2, 3, 4, 5])
f_x = np.array([2, 1.8, -2, -4.6, 3.6])

# Interpolación de Lagrange
polinomio_lagrange = lagrange(x, f_x)

# Coeficientes del polinomio de Lagrange
coeficientes = polinomio_lagrange.coefficients
print("Coeficientes del polinomio de Lagrange:", coeficientes)

# Graficar
x_graf = np.linspace(min(x), max(x), 100)
f_lagrange_graf = polinomio_lagrange(x_graf)

plt.figure(figsize=(10, 6))

# Puntos originales
plt.plot(x, f_x, 'o', label='Puntos originales')

# Polinomio de Lagrange
plt.plot(x_graf, f_lagrange_graf, label='Interpolación de Lagrange')

plt.legend()
plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('Interpolación Polinómica de Lagrange')
plt.grid(True)
plt.show()