# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xoWbKwfFArL97VYbGgIKW0cSYc9IpgzS
"""

import numpy as np

def exp_model_params(x, y):
    # Reorganiza x y transponlo
    x = np.array(x).reshape(-1, 1)
    x = np.transpose(x)

    # Calcula las medias
    x_mean = np.mean(x, axis=1)
    y_mean = np.mean(y)

    # Calcula la matriz de covarianza
    cov_matrix = np.cov(x, y, ddof=0)

    # Calcula los parámetros
    a = cov_matrix[0, 1] / cov_matrix[1, 1]
    b = y_mean - a * x_mean

    return a, b

x = [1, 2, 3, 4, 5, 6]
y = [1.6, 2.3, 3.4, 4.5, 6.4, 9]

a, b = exp_model_params(x, y)

# Aplica el modelo exponencial
y_pred = np.exp(a * np.array(x) + b)

print("Parámetros del Modelo Exponencial: a =", a, ", b =", b)
print("Valores de y predichos:", y_pred)