# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JHTUTANyIlQCi-tVEbLxmkVP-5UmUuc2
"""

import math

def aproximacion1(x, tolerancia=1e-8):
    resultado = 1.0
    termino = 1.0
    i = 1

    while abs(termino) > tolerancia:
        termino *= -x / i
        resultado += termino
        i += 1

    ea = abs((math.exp(-x) - resultado) / math.exp(-x)) * 100

    return resultado, ea, i - 1

def aproximacion2(x, tolerancia=1e-8):
    resultado = 1.0
    termino = 1.0
    i = 1

    while abs(termino) > tolerancia:
        termino *= x / i
        resultado += termino
        i += 1

    ea = abs((math.exp(-x) - 1 / resultado) / math.exp(-x)) * 100

    return resultado, ea, i - 1

def main():
    x_valor = 0.75

    # Aproximación 1
    resultado1, ea1, iteraciones1 = aproximacion1(x_valor)
    print("Aproximación 1:")
    print(f"Resultado: {resultado1:.8f}")
    print(f"Error relativo porcentual aproximado (εa): {ea1:.8f}%")
    print(f"Número de iteraciones: {iteraciones1}\n")

    # Aproximación 2
    resultado2, ea2, iteraciones2 = aproximacion2(x_valor)
    print("Aproximación 2:")
    print(f"Resultado: {resultado2:.8f}")
    print(f"Error relativo porcentual aproximado (εa): {ea2:.8f}%")
    print(f"Número de iteraciones: {iteraciones2}")

if __name__ == "__main__":
    main()