# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZsR7VKYsvRXEAiiQ5jQDw9RPRb_rP2G
"""

import numpy as np
from scipy.stats import pearsonr

# Datos
x = np.array([1, 3, 5, 7, 9, 11, 13])
y = np.array([7.4, 1.8, -1, -1.8, -1.2, 2.2, 7.2])

# Ajuste polinomial de segundo grado
coefficients = np.polyfit(x, y, 2)
p = np.poly1d(coefficients)

# Coeficiente de correlación (r)
r, _ = pearsonr(x, y)

print("Coeficientes del polinomio de segundo grado:")
print(p)

print("\nCoeficiente de correlación (r):", r)