# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZgvZwdpTXk6uktHUVpXl8FEPf-AJ6aV
"""

from decimal import Decimal


a = Decimal("75.20253")
b = Decimal("0.009997")
c = Decimal("533.075")
d = Decimal("38.611007")
e = Decimal("0.38654")
f = Decimal("0.00012097")
g = Decimal("37.86093")
h = Decimal("0.000103862")


resultado_a = a + b
resultado_b = c - d
resultado_c = e * f
resultado_d = g / h


print("Resultado de la operación a):", resultado_a)
print("Resultado de la operación b):", resultado_b)
print("Resultado de la operación c):", resultado_c)
print("Resultado de la operación d):", resultado_d)