# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FpsBdmDckGX4hU40lkRmYUV82klocGPW
"""

import math

# Definir la función y sus derivadas
def f(a):
    return math.exp(-a)

# Punto base
a = 0.5

# Calcular el valor exacto
exact_value = f(0.505)

# Inicializar variables
value_approx = f(a)
error_percent = 0
signo = -1

print("Orden\tValor Aproximado\tError Porcentual")

# Calcular la aproximación de la función y el error para cada término de la serie de Taylor
for n in range(1, 16):
    valant = value_approx
    value_approx += signo * (f(a) * (0.005) ** n) / math.factorial(n)

    error_percent = abs((valant - value_approx) / value_approx) * 100

    print(f"{n}\t{value_approx}\t{error_percent}")
    signo = signo * -1